version: '3'

services:
  orders-db:
    container_name: orders_database
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Amoica111425!
      - MYSQL_USER=amoica
      - MYSQL_PASSWORD=amoica111425
      - MYSQL_DATABASE=ordersdb